name: Build and test Go
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"

      - run: go version

      - run: go test -v ./...

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
