name: Build and test Go
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Test
        run: go test -v ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
