name: Build and test Go
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
